[jenkins]
prefix = "/"

[jenkins.session]
timeout = 60

[jenkins.http]
enabled = true
port = 8080
httpListenAddress = '0.0.0.0'

[jenkins.https]
enabled = false
port = 443

[jenkins.http2]
enabled = false
port = 80

[jenkins.ajp13]
enabled = false
port = 8009

[java]
opts = "-Djenkins.install.runSetupWizard=false"

[admin]
username = "admin"
password = "admin"
emailAddress = "gregs@indellient.com"

[config]
swarmHost = "unix:///var/run/docker.sock"
jenkinsRoot = "http://ci.example.com"
slavePort = 9999
plugins = [
  "git",
  "github",
  "github-oauth",
  "cloudbees-folder",
  "configuration-as-code",
  "configuration-as-code-support",
  "credentials",
  "token-macro",
  "blueocean",
  "job-dsl",
  "view-job-filters",
  "embeddable-build-status",
  "groovy",
  "dashboard-view",
  "rich-text-publisher-plugin",
  "console-column-plugin",
  "docker-plugin",
  "hashicorp-vault-plugin",
  "habitat",
  "github-oauth"
]
