jenkins:
  slaveAgentPort: 9999
  agentProtocols:
    - "JNLP4-connect"
  remotingSecurity:
    enabled: true
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      users:
        -
          id: "{{cfg.admin.username}}"
          password: "{{cfg.admin.password}}"
  clouds:
    - docker:
        name: "docker-swarm"
        dockerApi:
          dockerHost:
            uri: "{{cfg.config.swarmHost}}"
        templates:
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "jenkins/jnlp-slave"
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "10"
unclassified:
  location:
    adminAddress: {{cfg.admin.emailAddress}}
    url: {{cfg.config.jenkinsRoot}}
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
